import { NextResponse, type NextRequest } from 'next/server';
import { db, getAuthUser, logActivity } from '@/lib/api-helpers';

export async function GET(req: NextRequest) {
  const u = getAuthUser(req);
  if (!u) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  const { searchParams } = new URL(req.url);
  const id = searchParams.get('id');
  if (id) {
    const report = await db.report.findUnique({ where: { id } });
    if (!report) return NextResponse.json({ error: 'Not found' }, { status: 404 });
    return NextResponse.json(report);
  }
  return NextResponse.json(await db.report.findMany({ orderBy: { generatedAt: 'desc' } }));
}

export async function POST(req: NextRequest) {
  const user = getAuthUser(req);
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  try {
    const { title, template, period } = await req.json();
    if (!title || !template) return NextResponse.json({ error: 'title and template required' }, { status: 400 });

    const report = await db.report.create({
      data: { title, template, period: period || '—', status: 'processing' },
    });

    // Generar PDF asíncrono
    generateReportPdf(report.id, title, template, period || '—').catch(console.error);

    await logActivity('report', `Reporte generado: ${title}`, 'info', user.username);
    return NextResponse.json(report, { status: 201 });
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}

async function generateReportPdf(reportId: string, title: string, template: string, period: string) {
  try {
    // Recopilar datos
    const [brands, threats, executives] = await Promise.all([
      db.brand.findMany(),
      db.threat.findMany({ orderBy: { detectedAt: 'desc' }, take: 20 }),
      db.executive.findMany(),
    ]);

    const critical = threats.filter(t => t.severity === 'critical').length;
    const high = threats.filter(t => t.severity === 'high').length;
    const medium = threats.filter(t => t.severity === 'medium').length;
    const low = threats.filter(t => t.severity === 'low').length;

    // Construir PDF minimal con sintaxis PDF nativa
    const lines: string[] = [];
    const now = new Date().toLocaleString();
    lines.push('BT');
    lines.push('/F1 24 Tf');
    lines.push('60 760 Td');
    lines.push(`(${escapePdf(title)}) Tj`);
    lines.push('/F1 11 Tf');
    lines.push('0 -30 Td');
    lines.push(`(DataCyber Intelligence Platform) Tj`);
    lines.push('0 -20 Td');
    lines.push(`(Generated: ${now}) Tj`);
    lines.push('0 -20 Td');
    lines.push(`(Template: ${escapePdf(template)}) Tj`);
    lines.push('0 -20 Td');
    lines.push(`(Period: ${escapePdf(period)}) Tj`);
    lines.push('0 -35 Td');
    lines.push('/F1 14 Tf');
    lines.push('(1. EXECUTIVE SUMMARY) Tj');
    lines.push('/F1 10 Tf');
    lines.push('0 -20 Td');
    lines.push(`(Brands monitored: ${brands.length}) Tj`);
    lines.push('0 -15 Td');
    lines.push(`(Active threats: ${threats.length}) Tj`);
    lines.push('0 -15 Td');
    lines.push(`(Critical: ${critical}   High: ${high}   Medium: ${medium}   Low: ${low}) Tj`);
    lines.push('0 -15 Td');
    lines.push(`(Executives monitored: ${executives.length}) Tj`);
    lines.push('0 -30 Td');
    lines.push('/F1 14 Tf');
    lines.push('(2. BRANDS MONITORED) Tj');
    lines.push('/F1 10 Tf');
    lines.push('0 -18 Td');
    for (const b of brands) {
      lines.push(`(${escapePdf(b.name + ' - ' + b.country + ' - ' + b.domain + ' - ' + b.status + ' - ' + b.findings + ' findings')}) Tj`);
      lines.push('0 -13 Td');
    }
    lines.push('0 -20 Td');
    lines.push('/F1 14 Tf');
    lines.push('(3. RECENT THREATS) Tj');
    lines.push('/F1 10 Tf');
    lines.push('0 -18 Td');
    for (const t of threats.slice(0, 15)) {
      lines.push(`(${escapePdf('[' + t.severity.toUpperCase() + '] ' + t.title.slice(0, 80))}) Tj`);
      lines.push('0 -13 Td');
    }
    lines.push('0 -25 Td');
    lines.push('/F1 9 Tf');
    lines.push('(--- Generated by DataCyber - SOC 2 Type II compliant ---) Tj');
    lines.push('ET');

    const contentStream = lines.join('\n');
    const pdf = buildMinimalPdf(contentStream);

    await db.report.update({
      where: { id: reportId },
      data: {
        status: 'ready',
        size: `${(pdf.length / 1024).toFixed(1)} KB`,
        content: JSON.stringify({ brands: brands.length, threats: threats.length, critical, high, medium, low }),
        pdfBase64: Buffer.from(pdf).toString('base64'),
      },
    });
  } catch (e: any) {
    await db.report.update({
      where: { id: reportId },
      data: { status: 'failed', size: '—', content: JSON.stringify({ error: e.message }) },
    });
  }
}

function escapePdf(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)').replace(/\n/g, ' ');
}

function buildMinimalPdf(contentStream: string): string {
  // PDF minimal válido con una página A4
  const objects: string[] = [];
  objects.push('<< /Type /Catalog /Pages 2 0 R >>');
  objects.push('<< /Type /Pages /Kids [3 0 R] /Count 1 >>');
  objects.push('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>');
  objects.push(`<< /Length ${contentStream.length} >>\nstream\n${contentStream}\nendstream`);
  objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];
  for (let i = 0; i < objects.length; i++) {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${objects[i]}\nendobj\n`;
  }
  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const off of offsets) {
    pdf += String(off).padStart(10, '0') + ' 00000 n \n';
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return pdf;
}
